# Python image to use.
FROM python:3.10-alpine

# Set the working directory to /app
WORKDIR /app

# copy the requirements file used for dependencies
COPY src/requirements.txt .

# Copy the rest of the working directory contents into the container at /app
COPY src/. .
COPY tests/. .

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt
# Run tests when the container launches
ENTRYPOINT ["python", "tests.py"]
