name: Run smoke tests on existing docker image
on:
  push:
    branches:
      - '**'
      - '!main'
  run_dh_container:
    runs-on: ubuntu-latest
    needs: branch_build_and_push

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: docker_pull
        if: success()
        run: |
          export REMOTE_TAG="${{ vars.DOCKERHUB_REPO }}:${{ env.BUILD_DOCKER_TAG }}"
          docker pull -q ${REMOTE_TAG}
          docker network ls
          
          export PORT=5000
          docker_id=$(docker run -d -e $PORT -p $PORT:$PORT --network bridge ${REMOTE_TAG})
          docker exec $docker_id  sh -c "wget -S -q 127.0.0.1:5000"